name: Build

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Version
        id: version
        shell: pwsh
        run: |
          $VersionConfig = Get-Content version.json | ConvertFrom-Json

          $Major = $VersionConfig.Major
          $Minor = $VersionConfig.Minor

          $Build = $env:GITHUB_RUN_NUMBER
          $Revision = (git rev-list --count HEAD)

          $Version = "$Major.$Minor.$Build.$Revision"

          "version=$Version" >> $env:GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}

      - name: Package Module
        shell: pwsh
        run: |
          New-Item -ItemType Directory `
            -Path .\output\mua `
            -Force | Out-Null

          Copy-Item `
            -Path .\mua\* `
            -Destination .\output\mua `
            -Recurse

          Update-ModuleManifest `
            -Path .\output\mua\mua.psd1 `
            -ModuleVersion $env:VERSION

      - name: Verify Manifest
        shell: pwsh
        run: |
          Test-ModuleManifest .\output\mua\mua.psd1

      - name: Upload Module
        uses: actions/upload-artifact@v4
        with:
          name: mua
          path: output/mua