name: Build

permissions:
  contents: write

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  version:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Version
        id: version
        shell: pwsh
        run: |
          $VersionConfig = Get-Content version.json | ConvertFrom-Json

          $Major = $VersionConfig.Major
          $Minor = $VersionConfig.Minor

          $Build = $env:GITHUB_RUN_NUMBER
          $Revision = (git rev-list --count HEAD)

          $Version = "$Major.$Minor.$Build.$Revision"

          Write-Host "Generated Version: $Version"

          "version=$Version" >> $env:GITHUB_OUTPUT

      - name: Show Version
        shell: pwsh
        run: |
          Write-Host "Version = ${{ steps.version.outputs.version }}"

      - name: Create Tag
        shell: pwsh
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          $Version = "${{ steps.version.outputs.version }}"

          if (git tag --list "v$Version") {
            Write-Host "Tag already exists."
          }
          else {
            git tag "v$Version"
            git push origin "v$Version"
          }

      - name: Debug Files
        shell: pwsh
        run: |
          Get-Location
          Get-ChildItem -Recurse

      - name: Package Module
        shell: pwsh
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          New-Item `
            -ItemType Directory `
            -Path .\output\mua `
            -Force | Out-Null

          Copy-Item `
            -Path .\* `
            -Destination .\output\mua `
            -Recurse `
            -Exclude output,.git

          Update-ModuleManifest `
            -Path .\mua.psd1 `
            -ModuleVersion $env:VERSION

      - name: Verify Manifest
        shell: pwsh
        run: |
          Test-ModuleManifest .\output\mua.psd1

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          generate_release_notes: true

      - name: Upload Module
        uses: actions/upload-artifact@v4
        with:
          name: mua-${{ steps.version.outputs.version }}
          path: output/mua
